#!/usr/bin/env python

import click
import docker
import time

@click.command()
@click.argument('action')
@click.argument('name')
def main(action, name):
    client = docker.from_env()

    #kick it on, do a healthcheck, and return the URL to hit
    if action == 'run':
        kwargs = {
            'detach': True,
            'name': name,
            'ports': {'8080/tcp': 8080}
        }
        container = client.containers.run("sudomilk/nippykindlangur:latest", **kwargs)
        hcheck_resp = healthcheck(container)
        if hcheck_resp == b'200':
            click.echo('Your app is running on http://127.0.0.1:8080/hello')

    #turn it off
    if action == 'stop':
        container = client.containers.get(name)
        container.stop()
        container.remove()

def healthcheck(container):
    hcheck = 'curl -sw %{http_code} --output /dev/null http://0.0.00:8080/hello'
    time.sleep(5)
    return container.exec_run(hcheck)

if __name__ == '__main__':
    main()
